# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import id_pb2
import geometry_pb2
import object_pb2
import lane_marking_pb2
import traffic_sign_pb2
import traffic_light_pb2
import lane_pb2
import road_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tile.proto',
  package='hdmap_proto',
  serialized_pb=_b('\n\ntile.proto\x12\x0bhdmap_proto\x1a\x08id.proto\x1a\x0egeometry.proto\x1a\x0cobject.proto\x1a\x12lane_marking.proto\x1a\x12traffic_sign.proto\x1a\x13traffic_light.proto\x1a\nlane.proto\x1a\nroad.proto\"\xb2\x06\n\x04Tile\x12 \n\x07tile_id\x18\x01 \x02(\x0b\x32\x0f.hdmap_proto.Id\x12\x1d\n\x03idx\x18\x02 \x02(\x0b\x32\x10.hdmap_proto.Idx\x12%\n\tmin_point\x18\x04 \x02(\x0b\x32\x12.hdmap_proto.Point\x12*\n\x05range\x18\x05 \x02(\x0e\x32\x1b.hdmap_proto.Tile.TileRange\x12\x1f\n\x06\x63hilds\x18\x06 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12&\n\rcrosswalk_ids\x18\n \x03(\x0b\x32\x0f.hdmap_proto.Id\x12%\n\x0cjunction_ids\x18\x0b \x03(\x0b\x32\x0f.hdmap_proto.Id\x12)\n\x10parkingspace_ids\x18\x0c \x03(\x0b\x32\x0f.hdmap_proto.Id\x12!\n\x08road_ids\x18\r \x03(\x0b\x32\x0f.hdmap_proto.Id\x12$\n\x0brefline_ids\x18\x0e \x03(\x0b\x32\x0f.hdmap_proto.Id\x12!\n\x08lane_ids\x18\x0f \x03(\x0b\x32\x0f.hdmap_proto.Id\x12%\n\x0cstopline_ids\x18\x10 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12&\n\rspeedbump_ids\x18\x11 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12!\n\x08pole_ids\x18\x12 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12\"\n\tboard_ids\x18\x13 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12!\n\x08zone_ids\x18\x14 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12)\n\x10lane_marking_ids\x18\x15 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12*\n\x11traffic_light_ids\x18\x16 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12)\n\x10traffic_sign_ids\x18\x17 \x03(\x0b\x32\x0f.hdmap_proto.Id\x12%\n\x0csections_ids\x18\x18 \x03(\x0b\x32\x0f.hdmap_proto.Id\"-\n\tTileRange\x12\x06\n\x02T0\x10(\x12\x06\n\x02T1\x10P\x12\x07\n\x02T2\x10\xa0\x01\x12\x07\n\x02T3\x10\xc0\x02')
  ,
  dependencies=[id_pb2.DESCRIPTOR,geometry_pb2.DESCRIPTOR,object_pb2.DESCRIPTOR,lane_marking_pb2.DESCRIPTOR,traffic_sign_pb2.DESCRIPTOR,traffic_light_pb2.DESCRIPTOR,lane_pb2.DESCRIPTOR,road_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TILE_TILERANGE = _descriptor.EnumDescriptor(
  name='TileRange',
  full_name='hdmap_proto.Tile.TileRange',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='T0', index=0, number=40,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='T1', index=1, number=80,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='T2', index=2, number=160,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='T3', index=3, number=320,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=926,
  serialized_end=971,
)
_sym_db.RegisterEnumDescriptor(_TILE_TILERANGE)


_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='hdmap_proto.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tile_id', full_name='hdmap_proto.Tile.tile_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idx', full_name='hdmap_proto.Tile.idx', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_point', full_name='hdmap_proto.Tile.min_point', index=2,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='hdmap_proto.Tile.range', index=3,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=40,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='childs', full_name='hdmap_proto.Tile.childs', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crosswalk_ids', full_name='hdmap_proto.Tile.crosswalk_ids', index=5,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='junction_ids', full_name='hdmap_proto.Tile.junction_ids', index=6,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parkingspace_ids', full_name='hdmap_proto.Tile.parkingspace_ids', index=7,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='road_ids', full_name='hdmap_proto.Tile.road_ids', index=8,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refline_ids', full_name='hdmap_proto.Tile.refline_ids', index=9,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_ids', full_name='hdmap_proto.Tile.lane_ids', index=10,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stopline_ids', full_name='hdmap_proto.Tile.stopline_ids', index=11,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speedbump_ids', full_name='hdmap_proto.Tile.speedbump_ids', index=12,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pole_ids', full_name='hdmap_proto.Tile.pole_ids', index=13,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='board_ids', full_name='hdmap_proto.Tile.board_ids', index=14,
      number=19, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone_ids', full_name='hdmap_proto.Tile.zone_ids', index=15,
      number=20, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_marking_ids', full_name='hdmap_proto.Tile.lane_marking_ids', index=16,
      number=21, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traffic_light_ids', full_name='hdmap_proto.Tile.traffic_light_ids', index=17,
      number=22, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traffic_sign_ids', full_name='hdmap_proto.Tile.traffic_sign_ids', index=18,
      number=23, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sections_ids', full_name='hdmap_proto.Tile.sections_ids', index=19,
      number=24, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TILE_TILERANGE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=971,
)

_TILE.fields_by_name['tile_id'].message_type = id_pb2._ID
_TILE.fields_by_name['idx'].message_type = id_pb2._IDX
_TILE.fields_by_name['min_point'].message_type = geometry_pb2._POINT
_TILE.fields_by_name['range'].enum_type = _TILE_TILERANGE
_TILE.fields_by_name['childs'].message_type = id_pb2._ID
_TILE.fields_by_name['crosswalk_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['junction_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['parkingspace_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['road_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['refline_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['lane_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['stopline_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['speedbump_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['pole_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['board_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['zone_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['lane_marking_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['traffic_light_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['traffic_sign_ids'].message_type = id_pb2._ID
_TILE.fields_by_name['sections_ids'].message_type = id_pb2._ID
_TILE_TILERANGE.containing_type = _TILE
DESCRIPTOR.message_types_by_name['Tile'] = _TILE

Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), dict(
  DESCRIPTOR = _TILE,
  __module__ = 'tile_pb2'
  # @@protoc_insertion_point(class_scope:hdmap_proto.Tile)
  ))
_sym_db.RegisterMessage(Tile)


# @@protoc_insertion_point(module_scope)
