// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "map.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hdmap_proto {

namespace {

const ::google::protobuf::Descriptor* Header_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Header_reflection_ = NULL;
const ::google::protobuf::Descriptor* Map_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Map_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_map_2eproto() {
  protobuf_AddDesc_map_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "map.proto");
  GOOGLE_CHECK(file != NULL);
  Header_descriptor_ = file->message_type(0);
  static const int Header_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, projection_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, low_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, high_),
  };
  Header_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Header_descriptor_,
      Header::default_instance_,
      Header_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Header, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Header));
  Map_descriptor_ = file->message_type(1);
  static const int Map_offsets_[15] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, sections_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, crosswalks_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, junctions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, stoplines_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, speedbumps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, poles_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, boards_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, zones_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, lane_markings_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, traffic_lights_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, traffic_signs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, parking_spaces_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, borders_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, tiles_),
  };
  Map_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Map_descriptor_,
      Map::default_instance_,
      Map_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Map, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Map));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_map_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Header_descriptor_, &Header::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Map_descriptor_, &Map::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_map_2eproto() {
  delete Header::default_instance_;
  delete Header_reflection_;
  delete Map::default_instance_;
  delete Map_reflection_;
}

void protobuf_AddDesc_map_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::hdmap_proto::protobuf_AddDesc_geometry_2eproto();
  ::hdmap_proto::protobuf_AddDesc_object_2eproto();
  ::hdmap_proto::protobuf_AddDesc_tile_2eproto();
  ::hdmap_proto::protobuf_AddDesc_lane_2eproto();
  ::hdmap_proto::protobuf_AddDesc_section_2eproto();
  ::hdmap_proto::protobuf_AddDesc_lane_5fmarking_2eproto();
  ::hdmap_proto::protobuf_AddDesc_traffic_5flight_2eproto();
  ::hdmap_proto::protobuf_AddDesc_traffic_5fsign_2eproto();
  ::hdmap_proto::protobuf_AddDesc_parking_5fspace_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tmap.proto\022\013hdmap_proto\032\016geometry.proto"
    "\032\014object.proto\032\ntile.proto\032\nlane.proto\032\r"
    "section.proto\032\022lane_marking.proto\032\023traff"
    "ic_light.proto\032\022traffic_sign.proto\032\023park"
    "ing_space.proto\"\204\001\n\006Header\022\017\n\007version\030\001 "
    "\001(\t\022\014\n\004date\030\002 \001(\t\022\022\n\nprojection\030\003 \001(\t\022\"\n"
    "\003low\030\004 \001(\0132\025.hdmap_proto.Vector3d\022#\n\004hig"
    "h\030\005 \001(\0132\025.hdmap_proto.Vector3d\"\364\004\n\003Map\022#"
    "\n\006header\030\001 \001(\0132\023.hdmap_proto.Header\022&\n\010s"
    "ections\030\002 \003(\0132\024.hdmap_proto.Section\022*\n\nc"
    "rosswalks\030\003 \003(\0132\026.hdmap_proto.CrossWalk\022"
    "(\n\tjunctions\030\004 \003(\0132\025.hdmap_proto.Junctio"
    "n\022(\n\tstoplines\030\005 \003(\0132\025.hdmap_proto.StopL"
    "ine\022*\n\nspeedbumps\030\006 \003(\0132\026.hdmap_proto.Sp"
    "eedBump\022 \n\005poles\030\007 \003(\0132\021.hdmap_proto.Pol"
    "e\022\"\n\006boards\030\010 \003(\0132\022.hdmap_proto.Board\022 \n"
    "\005zones\030\t \003(\0132\021.hdmap_proto.Zone\022/\n\rlane_"
    "markings\030\n \003(\0132\030.hdmap_proto.LaneMarking"
    "\0221\n\016traffic_lights\030\013 \003(\0132\031.hdmap_proto.T"
    "rafficLight\022/\n\rtraffic_signs\030\014 \003(\0132\030.hdm"
    "ap_proto.TrafficSign\0221\n\016parking_spaces\030\r"
    " \003(\0132\031.hdmap_proto.ParkingSpace\022\"\n\007borde"
    "rs\030\016 \003(\0132\021.hdmap_proto.Lane\022 \n\005tiles\030\017 \003"
    "(\0132\021.hdmap_proto.Tile", 941);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "map.proto", &protobuf_RegisterTypes);
  Header::default_instance_ = new Header();
  Map::default_instance_ = new Map();
  Header::default_instance_->InitAsDefaultInstance();
  Map::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_map_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_map_2eproto {
  StaticDescriptorInitializer_map_2eproto() {
    protobuf_AddDesc_map_2eproto();
  }
} static_descriptor_initializer_map_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Header::kVersionFieldNumber;
const int Header::kDateFieldNumber;
const int Header::kProjectionFieldNumber;
const int Header::kLowFieldNumber;
const int Header::kHighFieldNumber;
#endif  // !_MSC_VER

Header::Header()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap_proto.Header)
}

void Header::InitAsDefaultInstance() {
  low_ = const_cast< ::hdmap_proto::Vector3d*>(&::hdmap_proto::Vector3d::default_instance());
  high_ = const_cast< ::hdmap_proto::Vector3d*>(&::hdmap_proto::Vector3d::default_instance());
}

Header::Header(const Header& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hdmap_proto.Header)
}

void Header::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  projection_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  low_ = NULL;
  high_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:hdmap_proto.Header)
  SharedDtor();
}

void Header::SharedDtor() {
  if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete version_;
  }
  if (date_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete date_;
  }
  if (projection_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete projection_;
  }
  if (this != default_instance_) {
    delete low_;
    delete high_;
  }
}

void Header::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Header::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Header_descriptor_;
}

const Header& Header::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_map_2eproto();
  return *default_instance_;
}

Header* Header::default_instance_ = NULL;

Header* Header::New() const {
  return new Header;
}

void Header::Clear() {
  if (_has_bits_[0 / 32] & 31) {
    if (has_version()) {
      if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        version_->clear();
      }
    }
    if (has_date()) {
      if (date_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        date_->clear();
      }
    }
    if (has_projection()) {
      if (projection_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        projection_->clear();
      }
    }
    if (has_low()) {
      if (low_ != NULL) low_->::hdmap_proto::Vector3d::Clear();
    }
    if (has_high()) {
      if (high_ != NULL) high_->::hdmap_proto::Vector3d::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap_proto.Header)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string version = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->version().data(), this->version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "version");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_date;
        break;
      }

      // optional string date = 2;
      case 2: {
        if (tag == 18) {
         parse_date:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_date()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->date().data(), this->date().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "date");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_projection;
        break;
      }

      // optional string projection = 3;
      case 3: {
        if (tag == 26) {
         parse_projection:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_projection()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->projection().data(), this->projection().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "projection");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_low;
        break;
      }

      // optional .hdmap_proto.Vector3d low = 4;
      case 4: {
        if (tag == 34) {
         parse_low:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_low()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_high;
        break;
      }

      // optional .hdmap_proto.Vector3d high = 5;
      case 5: {
        if (tag == 42) {
         parse_high:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_high()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap_proto.Header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap_proto.Header)
  return false;
#undef DO_
}

void Header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap_proto.Header)
  // optional string version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->version(), output);
  }

  // optional string date = 2;
  if (has_date()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->date().data(), this->date().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "date");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->date(), output);
  }

  // optional string projection = 3;
  if (has_projection()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->projection().data(), this->projection().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "projection");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->projection(), output);
  }

  // optional .hdmap_proto.Vector3d low = 4;
  if (has_low()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->low(), output);
  }

  // optional .hdmap_proto.Vector3d high = 5;
  if (has_high()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->high(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap_proto.Header)
}

::google::protobuf::uint8* Header::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hdmap_proto.Header)
  // optional string version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->version(), target);
  }

  // optional string date = 2;
  if (has_date()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->date().data(), this->date().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "date");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->date(), target);
  }

  // optional string projection = 3;
  if (has_projection()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->projection().data(), this->projection().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "projection");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->projection(), target);
  }

  // optional .hdmap_proto.Vector3d low = 4;
  if (has_low()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->low(), target);
  }

  // optional .hdmap_proto.Vector3d high = 5;
  if (has_high()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->high(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap_proto.Header)
  return target;
}

int Header::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->version());
    }

    // optional string date = 2;
    if (has_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->date());
    }

    // optional string projection = 3;
    if (has_projection()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->projection());
    }

    // optional .hdmap_proto.Vector3d low = 4;
    if (has_low()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->low());
    }

    // optional .hdmap_proto.Vector3d high = 5;
    if (has_high()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->high());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Header::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Header* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Header*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Header::MergeFrom(const Header& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
    if (from.has_date()) {
      set_date(from.date());
    }
    if (from.has_projection()) {
      set_projection(from.projection());
    }
    if (from.has_low()) {
      mutable_low()->::hdmap_proto::Vector3d::MergeFrom(from.low());
    }
    if (from.has_high()) {
      mutable_high()->::hdmap_proto::Vector3d::MergeFrom(from.high());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Header::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Header::CopyFrom(const Header& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {

  if (has_low()) {
    if (!this->low().IsInitialized()) return false;
  }
  if (has_high()) {
    if (!this->high().IsInitialized()) return false;
  }
  return true;
}

void Header::Swap(Header* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(date_, other->date_);
    std::swap(projection_, other->projection_);
    std::swap(low_, other->low_);
    std::swap(high_, other->high_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Header::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Header_descriptor_;
  metadata.reflection = Header_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Map::kHeaderFieldNumber;
const int Map::kSectionsFieldNumber;
const int Map::kCrosswalksFieldNumber;
const int Map::kJunctionsFieldNumber;
const int Map::kStoplinesFieldNumber;
const int Map::kSpeedbumpsFieldNumber;
const int Map::kPolesFieldNumber;
const int Map::kBoardsFieldNumber;
const int Map::kZonesFieldNumber;
const int Map::kLaneMarkingsFieldNumber;
const int Map::kTrafficLightsFieldNumber;
const int Map::kTrafficSignsFieldNumber;
const int Map::kParkingSpacesFieldNumber;
const int Map::kBordersFieldNumber;
const int Map::kTilesFieldNumber;
#endif  // !_MSC_VER

Map::Map()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap_proto.Map)
}

void Map::InitAsDefaultInstance() {
  header_ = const_cast< ::hdmap_proto::Header*>(&::hdmap_proto::Header::default_instance());
}

Map::Map(const Map& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hdmap_proto.Map)
}

void Map::SharedCtor() {
  _cached_size_ = 0;
  header_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Map::~Map() {
  // @@protoc_insertion_point(destructor:hdmap_proto.Map)
  SharedDtor();
}

void Map::SharedDtor() {
  if (this != default_instance_) {
    delete header_;
  }
}

void Map::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Map::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Map_descriptor_;
}

const Map& Map::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_map_2eproto();
  return *default_instance_;
}

Map* Map::default_instance_ = NULL;

Map* Map::New() const {
  return new Map;
}

void Map::Clear() {
  if (has_header()) {
    if (header_ != NULL) header_->::hdmap_proto::Header::Clear();
  }
  sections_.Clear();
  crosswalks_.Clear();
  junctions_.Clear();
  stoplines_.Clear();
  speedbumps_.Clear();
  poles_.Clear();
  boards_.Clear();
  zones_.Clear();
  lane_markings_.Clear();
  traffic_lights_.Clear();
  traffic_signs_.Clear();
  parking_spaces_.Clear();
  borders_.Clear();
  tiles_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Map::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap_proto.Map)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .hdmap_proto.Header header = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sections;
        break;
      }

      // repeated .hdmap_proto.Section sections = 2;
      case 2: {
        if (tag == 18) {
         parse_sections:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_sections()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sections;
        if (input->ExpectTag(26)) goto parse_crosswalks;
        break;
      }

      // repeated .hdmap_proto.CrossWalk crosswalks = 3;
      case 3: {
        if (tag == 26) {
         parse_crosswalks:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_crosswalks()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_crosswalks;
        if (input->ExpectTag(34)) goto parse_junctions;
        break;
      }

      // repeated .hdmap_proto.Junction junctions = 4;
      case 4: {
        if (tag == 34) {
         parse_junctions:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_junctions()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_junctions;
        if (input->ExpectTag(42)) goto parse_stoplines;
        break;
      }

      // repeated .hdmap_proto.StopLine stoplines = 5;
      case 5: {
        if (tag == 42) {
         parse_stoplines:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_stoplines()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_stoplines;
        if (input->ExpectTag(50)) goto parse_speedbumps;
        break;
      }

      // repeated .hdmap_proto.SpeedBump speedbumps = 6;
      case 6: {
        if (tag == 50) {
         parse_speedbumps:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_speedbumps()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_speedbumps;
        if (input->ExpectTag(58)) goto parse_poles;
        break;
      }

      // repeated .hdmap_proto.Pole poles = 7;
      case 7: {
        if (tag == 58) {
         parse_poles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_poles()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_poles;
        if (input->ExpectTag(66)) goto parse_boards;
        break;
      }

      // repeated .hdmap_proto.Board boards = 8;
      case 8: {
        if (tag == 66) {
         parse_boards:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_boards()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_boards;
        if (input->ExpectTag(74)) goto parse_zones;
        break;
      }

      // repeated .hdmap_proto.Zone zones = 9;
      case 9: {
        if (tag == 74) {
         parse_zones:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_zones()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_zones;
        if (input->ExpectTag(82)) goto parse_lane_markings;
        break;
      }

      // repeated .hdmap_proto.LaneMarking lane_markings = 10;
      case 10: {
        if (tag == 82) {
         parse_lane_markings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_lane_markings()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_lane_markings;
        if (input->ExpectTag(90)) goto parse_traffic_lights;
        break;
      }

      // repeated .hdmap_proto.TrafficLight traffic_lights = 11;
      case 11: {
        if (tag == 90) {
         parse_traffic_lights:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_traffic_lights()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_traffic_lights;
        if (input->ExpectTag(98)) goto parse_traffic_signs;
        break;
      }

      // repeated .hdmap_proto.TrafficSign traffic_signs = 12;
      case 12: {
        if (tag == 98) {
         parse_traffic_signs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_traffic_signs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_traffic_signs;
        if (input->ExpectTag(106)) goto parse_parking_spaces;
        break;
      }

      // repeated .hdmap_proto.ParkingSpace parking_spaces = 13;
      case 13: {
        if (tag == 106) {
         parse_parking_spaces:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_parking_spaces()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_parking_spaces;
        if (input->ExpectTag(114)) goto parse_borders;
        break;
      }

      // repeated .hdmap_proto.Lane borders = 14;
      case 14: {
        if (tag == 114) {
         parse_borders:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_borders()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(114)) goto parse_borders;
        if (input->ExpectTag(122)) goto parse_tiles;
        break;
      }

      // repeated .hdmap_proto.Tile tiles = 15;
      case 15: {
        if (tag == 122) {
         parse_tiles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_tiles()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(122)) goto parse_tiles;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap_proto.Map)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap_proto.Map)
  return false;
#undef DO_
}

void Map::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap_proto.Map)
  // optional .hdmap_proto.Header header = 1;
  if (has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->header(), output);
  }

  // repeated .hdmap_proto.Section sections = 2;
  for (int i = 0; i < this->sections_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->sections(i), output);
  }

  // repeated .hdmap_proto.CrossWalk crosswalks = 3;
  for (int i = 0; i < this->crosswalks_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->crosswalks(i), output);
  }

  // repeated .hdmap_proto.Junction junctions = 4;
  for (int i = 0; i < this->junctions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->junctions(i), output);
  }

  // repeated .hdmap_proto.StopLine stoplines = 5;
  for (int i = 0; i < this->stoplines_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->stoplines(i), output);
  }

  // repeated .hdmap_proto.SpeedBump speedbumps = 6;
  for (int i = 0; i < this->speedbumps_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->speedbumps(i), output);
  }

  // repeated .hdmap_proto.Pole poles = 7;
  for (int i = 0; i < this->poles_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->poles(i), output);
  }

  // repeated .hdmap_proto.Board boards = 8;
  for (int i = 0; i < this->boards_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, this->boards(i), output);
  }

  // repeated .hdmap_proto.Zone zones = 9;
  for (int i = 0; i < this->zones_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, this->zones(i), output);
  }

  // repeated .hdmap_proto.LaneMarking lane_markings = 10;
  for (int i = 0; i < this->lane_markings_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->lane_markings(i), output);
  }

  // repeated .hdmap_proto.TrafficLight traffic_lights = 11;
  for (int i = 0; i < this->traffic_lights_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->traffic_lights(i), output);
  }

  // repeated .hdmap_proto.TrafficSign traffic_signs = 12;
  for (int i = 0; i < this->traffic_signs_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->traffic_signs(i), output);
  }

  // repeated .hdmap_proto.ParkingSpace parking_spaces = 13;
  for (int i = 0; i < this->parking_spaces_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, this->parking_spaces(i), output);
  }

  // repeated .hdmap_proto.Lane borders = 14;
  for (int i = 0; i < this->borders_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      14, this->borders(i), output);
  }

  // repeated .hdmap_proto.Tile tiles = 15;
  for (int i = 0; i < this->tiles_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, this->tiles(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap_proto.Map)
}

::google::protobuf::uint8* Map::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hdmap_proto.Map)
  // optional .hdmap_proto.Header header = 1;
  if (has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->header(), target);
  }

  // repeated .hdmap_proto.Section sections = 2;
  for (int i = 0; i < this->sections_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->sections(i), target);
  }

  // repeated .hdmap_proto.CrossWalk crosswalks = 3;
  for (int i = 0; i < this->crosswalks_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->crosswalks(i), target);
  }

  // repeated .hdmap_proto.Junction junctions = 4;
  for (int i = 0; i < this->junctions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->junctions(i), target);
  }

  // repeated .hdmap_proto.StopLine stoplines = 5;
  for (int i = 0; i < this->stoplines_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->stoplines(i), target);
  }

  // repeated .hdmap_proto.SpeedBump speedbumps = 6;
  for (int i = 0; i < this->speedbumps_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->speedbumps(i), target);
  }

  // repeated .hdmap_proto.Pole poles = 7;
  for (int i = 0; i < this->poles_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->poles(i), target);
  }

  // repeated .hdmap_proto.Board boards = 8;
  for (int i = 0; i < this->boards_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, this->boards(i), target);
  }

  // repeated .hdmap_proto.Zone zones = 9;
  for (int i = 0; i < this->zones_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        9, this->zones(i), target);
  }

  // repeated .hdmap_proto.LaneMarking lane_markings = 10;
  for (int i = 0; i < this->lane_markings_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, this->lane_markings(i), target);
  }

  // repeated .hdmap_proto.TrafficLight traffic_lights = 11;
  for (int i = 0; i < this->traffic_lights_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->traffic_lights(i), target);
  }

  // repeated .hdmap_proto.TrafficSign traffic_signs = 12;
  for (int i = 0; i < this->traffic_signs_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, this->traffic_signs(i), target);
  }

  // repeated .hdmap_proto.ParkingSpace parking_spaces = 13;
  for (int i = 0; i < this->parking_spaces_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, this->parking_spaces(i), target);
  }

  // repeated .hdmap_proto.Lane borders = 14;
  for (int i = 0; i < this->borders_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        14, this->borders(i), target);
  }

  // repeated .hdmap_proto.Tile tiles = 15;
  for (int i = 0; i < this->tiles_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        15, this->tiles(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap_proto.Map)
  return target;
}

int Map::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .hdmap_proto.Header header = 1;
    if (has_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->header());
    }

  }
  // repeated .hdmap_proto.Section sections = 2;
  total_size += 1 * this->sections_size();
  for (int i = 0; i < this->sections_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->sections(i));
  }

  // repeated .hdmap_proto.CrossWalk crosswalks = 3;
  total_size += 1 * this->crosswalks_size();
  for (int i = 0; i < this->crosswalks_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->crosswalks(i));
  }

  // repeated .hdmap_proto.Junction junctions = 4;
  total_size += 1 * this->junctions_size();
  for (int i = 0; i < this->junctions_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->junctions(i));
  }

  // repeated .hdmap_proto.StopLine stoplines = 5;
  total_size += 1 * this->stoplines_size();
  for (int i = 0; i < this->stoplines_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->stoplines(i));
  }

  // repeated .hdmap_proto.SpeedBump speedbumps = 6;
  total_size += 1 * this->speedbumps_size();
  for (int i = 0; i < this->speedbumps_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->speedbumps(i));
  }

  // repeated .hdmap_proto.Pole poles = 7;
  total_size += 1 * this->poles_size();
  for (int i = 0; i < this->poles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->poles(i));
  }

  // repeated .hdmap_proto.Board boards = 8;
  total_size += 1 * this->boards_size();
  for (int i = 0; i < this->boards_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->boards(i));
  }

  // repeated .hdmap_proto.Zone zones = 9;
  total_size += 1 * this->zones_size();
  for (int i = 0; i < this->zones_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->zones(i));
  }

  // repeated .hdmap_proto.LaneMarking lane_markings = 10;
  total_size += 1 * this->lane_markings_size();
  for (int i = 0; i < this->lane_markings_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->lane_markings(i));
  }

  // repeated .hdmap_proto.TrafficLight traffic_lights = 11;
  total_size += 1 * this->traffic_lights_size();
  for (int i = 0; i < this->traffic_lights_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->traffic_lights(i));
  }

  // repeated .hdmap_proto.TrafficSign traffic_signs = 12;
  total_size += 1 * this->traffic_signs_size();
  for (int i = 0; i < this->traffic_signs_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->traffic_signs(i));
  }

  // repeated .hdmap_proto.ParkingSpace parking_spaces = 13;
  total_size += 1 * this->parking_spaces_size();
  for (int i = 0; i < this->parking_spaces_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->parking_spaces(i));
  }

  // repeated .hdmap_proto.Lane borders = 14;
  total_size += 1 * this->borders_size();
  for (int i = 0; i < this->borders_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->borders(i));
  }

  // repeated .hdmap_proto.Tile tiles = 15;
  total_size += 1 * this->tiles_size();
  for (int i = 0; i < this->tiles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tiles(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Map::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Map* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Map*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Map::MergeFrom(const Map& from) {
  GOOGLE_CHECK_NE(&from, this);
  sections_.MergeFrom(from.sections_);
  crosswalks_.MergeFrom(from.crosswalks_);
  junctions_.MergeFrom(from.junctions_);
  stoplines_.MergeFrom(from.stoplines_);
  speedbumps_.MergeFrom(from.speedbumps_);
  poles_.MergeFrom(from.poles_);
  boards_.MergeFrom(from.boards_);
  zones_.MergeFrom(from.zones_);
  lane_markings_.MergeFrom(from.lane_markings_);
  traffic_lights_.MergeFrom(from.traffic_lights_);
  traffic_signs_.MergeFrom(from.traffic_signs_);
  parking_spaces_.MergeFrom(from.parking_spaces_);
  borders_.MergeFrom(from.borders_);
  tiles_.MergeFrom(from.tiles_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_header()) {
      mutable_header()->::hdmap_proto::Header::MergeFrom(from.header());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Map::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Map::CopyFrom(const Map& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Map::IsInitialized() const {

  if (has_header()) {
    if (!this->header().IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->sections())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->crosswalks())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->junctions())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->stoplines())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->speedbumps())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->poles())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->boards())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->zones())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->lane_markings())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->traffic_lights())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->traffic_signs())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->parking_spaces())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->borders())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->tiles())) return false;
  return true;
}

void Map::Swap(Map* other) {
  if (other != this) {
    std::swap(header_, other->header_);
    sections_.Swap(&other->sections_);
    crosswalks_.Swap(&other->crosswalks_);
    junctions_.Swap(&other->junctions_);
    stoplines_.Swap(&other->stoplines_);
    speedbumps_.Swap(&other->speedbumps_);
    poles_.Swap(&other->poles_);
    boards_.Swap(&other->boards_);
    zones_.Swap(&other->zones_);
    lane_markings_.Swap(&other->lane_markings_);
    traffic_lights_.Swap(&other->traffic_lights_);
    traffic_signs_.Swap(&other->traffic_signs_);
    parking_spaces_.Swap(&other->parking_spaces_);
    borders_.Swap(&other->borders_);
    tiles_.Swap(&other->tiles_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Map::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Map_descriptor_;
  metadata.reflection = Map_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap_proto

// @@protoc_insertion_point(global_scope)
